### PR TITLE
Add HTTP & S3 Handlers

### PR DESCRIPTION
**Pull request by thomascoquet**
Hi Thomas,
I added S3 and HTTP handlers to `osio`.
Have not tested them yet in real application scenarios, but I was thinking you could give early feedbacks if needed.
Only question I have is related to the copyright for the new files? Should i add my company?
Thomas

### CODE REVIEW

**Review by tbonfort — APPROVED** [review]
Thanks Thomas, LGTM as is, let me know when you have some real-world feedback.  For the copyright, you should add yourself and probably company to the contributed files.

**Comment by tbonfort** [comment]
please also update README

**Comment by tbonfort** [comment]
@thomascoquet is this PR ready for merge?

**Comment by thomascoquet** [comment]
Hi Thomas, I had to add HEAD requests to get file size. If you're okay with that, we can merge.

**Pull request merged**
