### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by cyril1929**

### CODE REVIEW

**Comment by tbonfort** [comment]
could you please also update the tested go versions to 1.21 and 1.22 in the github actions

**Comment by cyril1929** [comment]
Do I leave the minimum go version at 1.16 in the go.mod file? Or do I increase it too?

**Comment by tbonfort** [comment]
> Do I leave the minimum go version at 1.16 in the go.mod file? Or do I increase it too?

I doesn't need to be updated

**Comment by tbonfort** [comment]
tagged as v0.1.4

**Comment by cyril1929** [comment]
Thank a lot for your responsiveness !

**Pull request merged**
